package com.renda.merchantops.api.doc;

public final class OpenApiExamples {

    private OpenApiExamples() {
    }

    public static final String LOGIN_REQUEST_ADMIN = "{\"tenantCode\":\"demo-shop\",\"username\":\"admin\",\"password\":\"123456\"}";
    public static final String LOGIN_REQUEST_OPS = "{\"tenantCode\":\"demo-shop\",\"username\":\"ops\",\"password\":\"123456\"}";
    public static final String LOGIN_REQUEST_VIEWER = "{\"tenantCode\":\"demo-shop\",\"username\":\"viewer\",\"password\":\"123456\"}";
    public static final String REQ_DEV_ECHO = "{\"message\":\"hello merchantops\"}";
    public static final String REQ_USER_CREATE = "{\"username\":\"cashier\",\"displayName\":\"Cashier User\",\"email\":\"cashier@demo-shop.local\",\"password\":\"123456\",\"roleCodes\":[\"READ_ONLY\"]}";
    public static final String REQ_USER_UPDATE = "{\"displayName\":\"Updated Cashier\",\"email\":\"cashier.updated@demo-shop.local\"}";
    public static final String REQ_USER_STATUS_UPDATE = "{\"status\":\"DISABLED\"}";
    public static final String REQ_USER_ROLE_ASSIGNMENT = "{\"roleCodes\":[\"TENANT_ADMIN\"]}";
    public static final String REQ_TICKET_CREATE = "{\"title\":\"POS printer offline\",\"description\":\"Store POS printer stopped responding during lunch peak.\"}";
    public static final String REQ_TICKET_ASSIGN = "{\"assigneeId\":2}";
    public static final String REQ_TICKET_STATUS_UPDATE = "{\"status\":\"IN_PROGRESS\"}";
    public static final String REQ_TICKET_COMMENT_CREATE = "{\"content\":\"Checked the store network. Restarting the printer now.\"}";
    public static final String REQ_FEATURE_FLAG_UPDATE = "{\"enabled\":false}";

    public static final String RESP_SUCCESS_LOGIN = "{\"code\":\"SUCCESS\",\"message\":\"ok\",\"data\":{\"accessToken\":\"<jwt-token>\",\"tokenType\":\"Bearer\",\"expiresIn\":7200}}";
    public static final String RESP_BAD_REQUEST_CREDENTIAL = "{\"code\":\"BAD_REQUEST\",\"message\":\"username or password is incorrect\",\"data\":null}";
    public static final String RESP_FORBIDDEN_USER_INACTIVE = "{\"code\":\"FORBIDDEN\",\"message\":\"user is not active\",\"data\":null}";
    public static final String RESP_BAD_REQUEST_USERNAME_EXISTS = "{\"code\":\"BAD_REQUEST\",\"message\":\"username already exists in tenant\",\"data\":null}";
    public static final String RESP_BAD_REQUEST_ROLE_CODES = "{\"code\":\"BAD_REQUEST\",\"message\":\"roleCodes must exist in current tenant\",\"data\":null}";

    public static final String RESP_UNAUTHORIZED = "{\"code\":\"UNAUTHORIZED\",\"message\":\"authentication required\",\"data\":null}";
    public static final String RESP_FORBIDDEN = "{\"code\":\"FORBIDDEN\",\"message\":\"permission denied\",\"data\":null}";
    public static final String RESP_SERVICE_UNAVAILABLE_AI_DISABLED = "{\"code\":\"SERVICE_UNAVAILABLE\",\"message\":\"ticket ai summary is disabled\",\"data\":null}";
    public static final String RESP_SERVICE_UNAVAILABLE_AI_PROVIDER = "{\"code\":\"SERVICE_UNAVAILABLE\",\"message\":\"ticket ai summary is unavailable\",\"data\":null}";
    public static final String RESP_SERVICE_UNAVAILABLE_AI_REPLY_DRAFT_DISABLED = "{\"code\":\"SERVICE_UNAVAILABLE\",\"message\":\"ticket ai reply draft is disabled\",\"data\":null}";
    public static final String RESP_SERVICE_UNAVAILABLE_AI_REPLY_DRAFT_PROVIDER = "{\"code\":\"SERVICE_UNAVAILABLE\",\"message\":\"ticket ai reply draft is unavailable\",\"data\":null}";
    public static final String RESP_SERVICE_UNAVAILABLE_AI_TRIAGE_DISABLED = "{\"code\":\"SERVICE_UNAVAILABLE\",\"message\":\"ticket ai triage is disabled\",\"data\":null}";
    public static final String RESP_SERVICE_UNAVAILABLE_AI_TRIAGE_PROVIDER = "{\"code\":\"SERVICE_UNAVAILABLE\",\"message\":\"ticket ai triage is unavailable\",\"data\":null}";
    public static final String RESP_SERVICE_UNAVAILABLE_IMPORT_AI_ERROR_SUMMARY_DISABLED = "{\"code\":\"SERVICE_UNAVAILABLE\",\"message\":\"import ai error summary is disabled\",\"data\":null}";
    public static final String RESP_SERVICE_UNAVAILABLE_IMPORT_AI_ERROR_SUMMARY_PROVIDER = "{\"code\":\"SERVICE_UNAVAILABLE\",\"message\":\"import ai error summary is unavailable\",\"data\":null}";
    public static final String RESP_SERVICE_UNAVAILABLE_IMPORT_AI_MAPPING_SUGGESTION_DISABLED = "{\"code\":\"SERVICE_UNAVAILABLE\",\"message\":\"import ai mapping suggestion is disabled\",\"data\":null}";
    public static final String RESP_SERVICE_UNAVAILABLE_IMPORT_AI_MAPPING_SUGGESTION_PROVIDER = "{\"code\":\"SERVICE_UNAVAILABLE\",\"message\":\"import ai mapping suggestion is unavailable\",\"data\":null}";
    public static final String RESP_SERVICE_UNAVAILABLE_IMPORT_AI_FIX_RECOMMENDATION_DISABLED = "{\"code\":\"SERVICE_UNAVAILABLE\",\"message\":\"import ai fix recommendation is disabled\",\"data\":null}";
    public static final String RESP_SERVICE_UNAVAILABLE_IMPORT_AI_FIX_RECOMMENDATION_PROVIDER = "{\"code\":\"SERVICE_UNAVAILABLE\",\"message\":\"import ai fix recommendation is unavailable\",\"data\":null}";
    public static final String RESP_BAD_REQUEST_IMPORT_AI_MAPPING_SUGGESTION_NO_FAILURE_SIGNAL = "{\"code\":\"BAD_REQUEST\",\"message\":\"import job has no failure signals for mapping suggestion\",\"data\":null}";
    public static final String RESP_BAD_REQUEST_IMPORT_AI_MAPPING_SUGGESTION_NO_HEADER_SIGNAL = "{\"code\":\"BAD_REQUEST\",\"message\":\"import job has no sanitized header signal for mapping suggestion\",\"data\":null}";
    public static final String RESP_BAD_REQUEST_IMPORT_AI_FIX_RECOMMENDATION_NO_FAILURE_SIGNAL = "{\"code\":\"BAD_REQUEST\",\"message\":\"import job has no failure signals for fix recommendation\",\"data\":null}";
    public static final String RESP_BAD_REQUEST_IMPORT_AI_FIX_RECOMMENDATION_UNSUPPORTED_IMPORT_TYPE = "{\"code\":\"BAD_REQUEST\",\"message\":\"import ai fix recommendation only supports USER_CSV\",\"data\":null}";
    public static final String RESP_BAD_REQUEST_IMPORT_AI_FIX_RECOMMENDATION_NO_ROW_SIGNAL = "{\"code\":\"BAD_REQUEST\",\"message\":\"import job has no sanitized row signal for fix recommendation\",\"data\":null}";
    public static final String RESP_VALIDATION_ERROR_ECHO = "{\"code\":\"VALIDATION_ERROR\",\"message\":\"message: message must not be blank\",\"data\":null}";
    public static final String RESP_VALIDATION_ERROR_USER_CREATE = "{\"code\":\"VALIDATION_ERROR\",\"message\":\"username: username must not be blank\",\"data\":null}";
    public static final String RESP_VALIDATION_ERROR_PASSWORD_WHITESPACE = "{\"code\":\"VALIDATION_ERROR\",\"message\":\"password: password must not start or end with whitespace\",\"data\":null}";
    public static final String RESP_VALIDATION_ERROR_USER_UPDATE = "{\"code\":\"VALIDATION_ERROR\",\"message\":\"displayName: displayName must not be blank\",\"data\":null}";
    public static final String RESP_VALIDATION_ERROR_STATUS_UPDATE = "{\"code\":\"VALIDATION_ERROR\",\"message\":\"status: status must be one of ACTIVE, DISABLED\",\"data\":null}";
    public static final String RESP_VALIDATION_ERROR_ROLE_ASSIGNMENT = "{\"code\":\"VALIDATION_ERROR\",\"message\":\"roleCodes: roleCodes must not be empty\",\"data\":null}";
    public static final String RESP_VALIDATION_ERROR_TICKET_CREATE = "{\"code\":\"VALIDATION_ERROR\",\"message\":\"title: title must not be blank\",\"data\":null}";
    public static final String RESP_VALIDATION_ERROR_TICKET_ASSIGN = "{\"code\":\"VALIDATION_ERROR\",\"message\":\"assigneeId: assigneeId must not be null\",\"data\":null}";
    public static final String RESP_VALIDATION_ERROR_TICKET_STATUS = "{\"code\":\"VALIDATION_ERROR\",\"message\":\"status: status must be one of OPEN, IN_PROGRESS, CLOSED\",\"data\":null}";
    public static final String RESP_VALIDATION_ERROR_TICKET_COMMENT_CREATE = "{\"code\":\"VALIDATION_ERROR\",\"message\":\"content: content must not be blank\",\"data\":null}";

    public static final String RESP_HEALTH = "{\"status\":\"UP\",\"service\":\"merchantops-saas\"}";
    public static final String RESP_CONTEXT = "{\"code\":\"SUCCESS\",\"message\":\"ok\",\"data\":{\"tenantId\":1,\"tenantCode\":\"demo-shop\",\"userId\":1,\"username\":\"admin\"}}";
    public static final String RESP_USER_PROFILE = "{\"code\":\"SUCCESS\",\"message\":\"ok\",\"data\":{\"userId\":1,\"tenantId\":1,\"tenantCode\":\"demo-shop\",\"username\":\"admin\",\"roles\":[\"TENANT_ADMIN\"],\"permissions\":[\"USER_READ\",\"USER_WRITE\",\"ORDER_READ\",\"BILLING_READ\",\"FEATURE_FLAG_MANAGE\",\"TICKET_READ\",\"TICKET_WRITE\"]}}";
    public static final String RESP_USER_LIST = "{\"code\":\"SUCCESS\",\"message\":\"ok\",\"data\":{\"items\":[{\"id\":1,\"username\":\"admin\",\"displayName\":\"Demo Admin\",\"email\":\"admin@demo-shop.local\",\"status\":\"ACTIVE\"},{\"id\":2,\"username\":\"ops\",\"displayName\":\"Ops User\",\"email\":\"ops@demo-shop.local\",\"status\":\"ACTIVE\"},{\"id\":3,\"username\":\"viewer\",\"displayName\":\"Viewer User\",\"email\":\"viewer@demo-shop.local\",\"status\":\"ACTIVE\"}],\"page\":0,\"size\":10,\"total\":3,\"totalPages\":1}}";
    public static final String RESP_USER_DETAIL = "{\"code\":\"SUCCESS\",\"message\":\"ok\",\"data\":{\"id\":3,\"tenantId\":1,\"username\":\"viewer\",\"displayName\":\"Viewer User\",\"email\":\"viewer@demo-shop.local\",\"status\":\"ACTIVE\",\"roleCodes\":[\"READ_ONLY\"],\"createdAt\":\"2026-03-10T10:00:00\",\"updatedAt\":\"2026-03-10T10:30:00\"}}";
    public static final String RESP_ROLE_LIST = "{\"code\":\"SUCCESS\",\"message\":\"ok\",\"data\":{\"items\":[{\"id\":11,\"roleCode\":\"TENANT_ADMIN\",\"roleName\":\"Tenant Admin\"},{\"id\":12,\"roleCode\":\"OPS_USER\",\"roleName\":\"Operations User\"},{\"id\":13,\"roleCode\":\"READ_ONLY\",\"roleName\":\"Read Only User\"}]}}";
    public static final String RESP_USER_CREATED = "{\"code\":\"SUCCESS\",\"message\":\"ok\",\"data\":{\"id\":5,\"tenantId\":1,\"username\":\"cashier\",\"displayName\":\"Cashier User\",\"email\":\"cashier@demo-shop.local\",\"status\":\"ACTIVE\",\"roleCodes\":[\"READ_ONLY\"],\"createdAt\":\"2026-03-10T11:00:00\",\"updatedAt\":\"2026-03-10T11:00:00\"}}";
    public static final String RESP_USER_PROFILE_UPDATED = "{\"code\":\"SUCCESS\",\"message\":\"ok\",\"data\":{\"id\":5,\"tenantId\":1,\"username\":\"cashier\",\"displayName\":\"Updated Cashier\",\"email\":\"cashier.updated@demo-shop.local\",\"status\":\"ACTIVE\",\"updatedAt\":\"2026-03-10T14:00:00\"}}";
    public static final String RESP_USER_STATUS_UPDATED = "{\"code\":\"SUCCESS\",\"message\":\"ok\",\"data\":{\"id\":5,\"tenantId\":1,\"username\":\"cashier\",\"displayName\":\"Updated Cashier\",\"email\":\"cashier.updated@demo-shop.local\",\"status\":\"DISABLED\",\"updatedAt\":\"2026-03-10T14:10:00\"}}";
    public static final String RESP_USER_ROLES_UPDATED = "{\"code\":\"SUCCESS\",\"message\":\"ok\",\"data\":{\"id\":3,\"tenantId\":1,\"username\":\"viewer\",\"roleCodes\":[\"TENANT_ADMIN\"],\"permissionCodes\":[\"USER_READ\",\"USER_WRITE\",\"ORDER_READ\",\"BILLING_READ\",\"FEATURE_FLAG_MANAGE\",\"TICKET_READ\",\"TICKET_WRITE\"],\"updatedAt\":\"2026-03-10T18:00:00\"}}";
    public static final String RESP_FORBIDDEN_STALE_TOKEN = "{\"code\":\"FORBIDDEN\",\"message\":\"token claims are stale, please login again\",\"data\":null}";
    public static final String RESP_BAD_REQUEST_TICKET_ASSIGNEE = "{\"code\":\"BAD_REQUEST\",\"message\":\"user must exist in current tenant\",\"data\":null}";
    public static final String RESP_BAD_REQUEST_TICKET_STATUS_TRANSITION = "{\"code\":\"BAD_REQUEST\",\"message\":\"ticket status transition is not allowed\",\"data\":null}";
    public static final String RESP_BAD_REQUEST_TICKET_LIST_FILTERS = "{\"code\":\"BAD_REQUEST\",\"message\":\"assigneeId cannot be combined with unassignedOnly=true\",\"data\":null}";
    public static final String RESP_TICKET_LIST = "{\"code\":\"SUCCESS\",\"message\":\"ok\",\"data\":{\"items\":[{\"id\":2,\"title\":\"Printer cable replacement\",\"status\":\"IN_PROGRESS\",\"assigneeId\":2,\"assigneeUsername\":\"ops\",\"createdAt\":\"2026-03-11T09:30:00\",\"updatedAt\":\"2026-03-11T10:15:00\"},{\"id\":1,\"title\":\"POS printer offline\",\"status\":\"OPEN\",\"assigneeId\":null,\"assigneeUsername\":null,\"createdAt\":\"2026-03-11T09:00:00\",\"updatedAt\":\"2026-03-11T09:00:00\"}],\"page\":0,\"size\":10,\"total\":2,\"totalPages\":1}}";
    public static final String RESP_TICKET_DETAIL = "{\"code\":\"SUCCESS\",\"message\":\"ok\",\"data\":{\"id\":2,\"tenantId\":1,\"title\":\"Printer cable replacement\",\"description\":\"Replace damaged USB cable for store printer.\",\"status\":\"IN_PROGRESS\",\"assigneeId\":2,\"assigneeUsername\":\"ops\",\"createdBy\":1,\"createdByUsername\":\"admin\",\"createdAt\":\"2026-03-11T09:30:00\",\"updatedAt\":\"2026-03-11T10:20:00\",\"comments\":[{\"id\":31,\"ticketId\":2,\"content\":\"Cable swap started.\",\"createdBy\":2,\"createdByUsername\":\"ops\",\"createdAt\":\"2026-03-11T10:05:00\"}],\"operationLogs\":[{\"id\":41,\"operationType\":\"CREATED\",\"detail\":\"ticket created\",\"operatorId\":1,\"operatorUsername\":\"admin\",\"createdAt\":\"2026-03-11T09:30:00\"},{\"id\":42,\"operationType\":\"ASSIGNED\",\"detail\":\"assigned to ops\",\"operatorId\":1,\"operatorUsername\":\"admin\",\"createdAt\":\"2026-03-11T09:35:00\"},{\"id\":43,\"operationType\":\"STATUS_CHANGED\",\"detail\":\"status changed from OPEN to IN_PROGRESS\",\"operatorId\":2,\"operatorUsername\":\"ops\",\"createdAt\":\"2026-03-11T10:00:00\"}]}}";
    public static final String RESP_TICKET_AI_INTERACTIONS = "{\"code\":\"SUCCESS\",\"message\":\"ok\",\"data\":{\"items\":[{\"id\":9003,\"interactionType\":\"TRIAGE\",\"status\":\"INVALID_RESPONSE\",\"outputSummary\":null,\"promptVersion\":\"ticket-triage-v1\",\"modelId\":\"gpt-4.1-mini\",\"latencyMs\":251,\"requestId\":\"ticket-ai-triage-invalid-response-1\",\"usagePromptTokens\":null,\"usageCompletionTokens\":null,\"usageTotalTokens\":null,\"usageCostMicros\":null,\"createdAt\":\"2026-03-22T09:00:00\"},{\"id\":9002,\"interactionType\":\"REPLY_DRAFT\",\"status\":\"SUCCEEDED\",\"outputSummary\":\"nextStep=Confirm whether the replacement restored printer health and note any blocker before moving toward closure.\",\"promptVersion\":\"ticket-reply-draft-v1\",\"modelId\":\"gpt-4.1-mini\",\"latencyMs\":436,\"requestId\":\"ticket-ai-reply-draft-req-1\",\"usagePromptTokens\":140,\"usageCompletionTokens\":88,\"usageTotalTokens\":228,\"usageCostMicros\":2100,\"createdAt\":\"2026-03-22T09:00:00\"},{\"id\":9001,\"interactionType\":\"SUMMARY\",\"status\":\"SUCCEEDED\",\"outputSummary\":\"Issue: Printer cable replacement is in progress under ops. Current: the ticket is assigned and the latest signal says cable swap started. Next: confirm the replacement outcome and close the ticket if the printer is healthy.\",\"promptVersion\":\"ticket-summary-v1\",\"modelId\":\"gpt-4.1-mini\",\"latencyMs\":412,\"requestId\":\"ticket-ai-summary-req-1\",\"usagePromptTokens\":120,\"usageCompletionTokens\":52,\"usageTotalTokens\":172,\"usageCostMicros\":1900,\"createdAt\":\"2026-03-22T08:30:00\"}],\"page\":0,\"size\":10,\"total\":3,\"totalPages\":1}}";
    public static final String RESP_AI_INTERACTION_USAGE_SUMMARY = "{\"code\":\"SUCCESS\",\"message\":\"ok\",\"data\":{\"from\":\"2026-04-01T00:00:00\",\"to\":\"2026-04-05T23:59:59\",\"totalInteractions\":6,\"succeededCount\":4,\"failedCount\":2,\"totalPromptTokens\":530,\"totalCompletionTokens\":263,\"totalTokens\":793,\"totalCostMicros\":6200,\"byInteractionType\":[{\"interactionType\":\"ERROR_SUMMARY\",\"count\":2,\"succeededCount\":1,\"failedCount\":1,\"totalTokens\":232,\"totalCostMicros\":0},{\"interactionType\":\"MAPPING_SUGGESTION\",\"count\":1,\"succeededCount\":1,\"failedCount\":0,\"totalTokens\":161,\"totalCostMicros\":2200},{\"interactionType\":\"REPLY_DRAFT\",\"count\":1,\"succeededCount\":1,\"failedCount\":0,\"totalTokens\":228,\"totalCostMicros\":2100},{\"interactionType\":\"SUMMARY\",\"count\":1,\"succeededCount\":1,\"failedCount\":0,\"totalTokens\":172,\"totalCostMicros\":1900},{\"interactionType\":\"TRIAGE\",\"count\":1,\"succeededCount\":0,\"failedCount\":1,\"totalTokens\":0,\"totalCostMicros\":0}],\"byStatus\":[{\"status\":\"SUCCEEDED\",\"count\":4,\"totalTokens\":773,\"totalCostMicros\":6200},{\"status\":\"INVALID_RESPONSE\",\"count\":1,\"totalTokens\":0,\"totalCostMicros\":0},{\"status\":\"PROVIDER_TIMEOUT\",\"count\":1,\"totalTokens\":20,\"totalCostMicros\":0}],\"byPromptVersion\":[{\"promptVersion\":\"import-error-summary-v1\",\"count\":2,\"succeededCount\":1,\"failedCount\":1,\"totalTokens\":232,\"totalCostMicros\":0},{\"promptVersion\":\"import-mapping-suggestion-v1\",\"count\":1,\"succeededCount\":1,\"failedCount\":0,\"totalTokens\":161,\"totalCostMicros\":2200},{\"promptVersion\":\"ticket-reply-draft-v1\",\"count\":1,\"succeededCount\":1,\"failedCount\":0,\"totalTokens\":228,\"totalCostMicros\":2100},{\"promptVersion\":\"ticket-summary-v1\",\"count\":1,\"succeededCount\":1,\"failedCount\":0,\"totalTokens\":172,\"totalCostMicros\":1900},{\"promptVersion\":\"ticket-triage-v1\",\"count\":1,\"succeededCount\":0,\"failedCount\":1,\"totalTokens\":0,\"totalCostMicros\":0}]}}";
    public static final String RESP_TICKET_AI_SUMMARY = "{\"code\":\"SUCCESS\",\"message\":\"ok\",\"data\":{\"ticketId\":2,\"summary\":\"Issue: Printer cable replacement is in progress under ops. Current: the ticket is assigned and the latest signal says cable swap started. Next: confirm the replacement outcome and close the ticket if the printer is healthy.\",\"promptVersion\":\"ticket-summary-v1\",\"modelId\":\"gpt-4.1-mini\",\"generatedAt\":\"2026-03-19T13:20:15\",\"latencyMs\":412,\"requestId\":\"ticket-ai-summary-req-1\"}}";
    public static final String RESP_TICKET_AI_REPLY_DRAFT = "{\"code\":\"SUCCESS\",\"message\":\"ok\",\"data\":{\"ticketId\":2,\"draftText\":\"Quick update from ops.\\n\\nThe ticket is still in progress and the latest ticket activity confirms the cable swap has started for the store printer issue.\\n\\nNext step: Confirm whether the replacement restored printer health and note any blocker before moving toward closure.\\n\\nI will add another internal update once the verification result is confirmed.\",\"opening\":\"Quick update from ops.\",\"body\":\"The ticket is still in progress and the latest ticket activity confirms the cable swap has started for the store printer issue.\",\"nextStep\":\"Confirm whether the replacement restored printer health and note any blocker before moving toward closure.\",\"closing\":\"I will add another internal update once the verification result is confirmed.\",\"promptVersion\":\"ticket-reply-draft-v1\",\"modelId\":\"gpt-4.1-mini\",\"generatedAt\":\"2026-03-21T15:10:15\",\"latencyMs\":436,\"requestId\":\"ticket-ai-reply-draft-req-1\"}}";
    public static final String RESP_TICKET_AI_TRIAGE = "{\"code\":\"SUCCESS\",\"message\":\"ok\",\"data\":{\"ticketId\":2,\"classification\":\"DEVICE_ISSUE\",\"priority\":\"HIGH\",\"reasoning\":\"The ticket describes a store printer problem affecting active operations and the latest signal shows work is still in progress, so it should be treated as a high-priority device issue.\",\"promptVersion\":\"ticket-triage-v1\",\"modelId\":\"gpt-4.1-mini\",\"generatedAt\":\"2026-03-21T14:20:15\",\"latencyMs\":418,\"requestId\":\"ticket-ai-triage-req-1\"}}";
    public static final String RESP_IMPORT_JOB_AI_INTERACTIONS = "{\"code\":\"SUCCESS\",\"message\":\"ok\",\"data\":{\"items\":[{\"id\":9103,\"interactionType\":\"FIX_RECOMMENDATION\",\"status\":\"INVALID_RESPONSE\",\"outputSummary\":null,\"promptVersion\":\"import-fix-recommendation-v1\",\"modelId\":\"gpt-4.1-mini\",\"latencyMs\":251,\"requestId\":\"import-ai-fix-recommendation-invalid-response-1\",\"usagePromptTokens\":null,\"usageCompletionTokens\":null,\"usageTotalTokens\":null,\"usageCostMicros\":null,\"createdAt\":\"2026-03-28T10:45:00\"},{\"id\":9102,\"interactionType\":\"MAPPING_SUGGESTION\",\"status\":\"SUCCEEDED\",\"outputSummary\":\"The failed header still looks close to the canonical USER_CSV schema, so the safest next step is to confirm the proposed field mappings before preparing any replay input.\",\"promptVersion\":\"import-mapping-suggestion-v1\",\"modelId\":\"gpt-4.1-mini\",\"latencyMs\":544,\"requestId\":\"import-ai-mapping-suggestion-req-1\",\"usagePromptTokens\":141,\"usageCompletionTokens\":71,\"usageTotalTokens\":212,\"usageCostMicros\":null,\"createdAt\":\"2026-03-28T10:42:00\"},{\"id\":9101,\"interactionType\":\"ERROR_SUMMARY\",\"status\":\"SUCCEEDED\",\"outputSummary\":\"The job is dominated by tenant role validation failures, with structurally complete rows and no evidence of CSV shape corruption in the sanitized prompt window.\",\"promptVersion\":\"import-error-summary-v1\",\"modelId\":\"gpt-4.1-mini\",\"latencyMs\":512,\"requestId\":\"import-ai-error-summary-req-1\",\"usagePromptTokens\":140,\"usageCompletionTokens\":72,\"usageTotalTokens\":212,\"usageCostMicros\":null,\"createdAt\":\"2026-03-28T10:40:00\"}],\"page\":0,\"size\":10,\"total\":3,\"totalPages\":1}}";
    public static final String RESP_IMPORT_JOB_AI_ERROR_SUMMARY = "{\"code\":\"SUCCESS\",\"message\":\"ok\",\"data\":{\"importJobId\":1201,\"summary\":\"The job is dominated by tenant role validation failures, with structurally complete rows and no evidence of CSV shape corruption in the sanitized prompt window.\",\"topErrorPatterns\":[\"UNKNOWN_ROLE appears on multiple rows where roleCodes is present but invalid for the current tenant.\",\"The prompt window rows are structurally complete, so the current failures look like business validation rather than malformed CSV input.\"],\"recommendedNextSteps\":[\"Review the current tenant role catalog and correct invalid roleCodes before retrying.\",\"Use import job detail and /errors to choose between edited replay and selective replay after the role fixes are confirmed.\"],\"promptVersion\":\"import-error-summary-v1\",\"modelId\":\"gpt-4.1-mini\",\"generatedAt\":\"2026-03-27T10:20:15\",\"latencyMs\":512,\"requestId\":\"import-ai-error-summary-req-1\"}}";
    public static final String RESP_IMPORT_JOB_AI_MAPPING_SUGGESTION = "{\"code\":\"SUCCESS\",\"message\":\"ok\",\"data\":{\"importJobId\":1202,\"summary\":\"The failed header still looks close to the canonical USER_CSV schema, so the safest next step is to confirm the proposed field mappings before preparing any replay input.\",\"suggestedFieldMappings\":[{\"canonicalField\":\"username\",\"observedColumnSignal\":{\"headerName\":\"login\",\"headerPosition\":1},\"reasoning\":\"`login` is the closest observed header for the tenant username field.\",\"reviewRequired\":false},{\"canonicalField\":\"displayName\",\"observedColumnSignal\":{\"headerName\":\"display_name\",\"headerPosition\":2},\"reasoning\":\"`display_name` is the closest semantic match for the displayName field.\",\"reviewRequired\":false},{\"canonicalField\":\"email\",\"observedColumnSignal\":{\"headerName\":\"email_address\",\"headerPosition\":3},\"reasoning\":\"`email_address` is the most likely email column.\",\"reviewRequired\":false},{\"canonicalField\":\"password\",\"observedColumnSignal\":{\"headerName\":\"passwd\",\"headerPosition\":4},\"reasoning\":\"`passwd` looks like the credential column, but operators should confirm naming before any replay preparation.\",\"reviewRequired\":true},{\"canonicalField\":\"roleCodes\",\"observedColumnSignal\":{\"headerName\":\"roles\",\"headerPosition\":5},\"reasoning\":\"`roles` is the closest available signal for the canonical roleCodes field.\",\"reviewRequired\":true}],\"confidenceNotes\":[\"The source file failed header validation, so each mapping should be reviewed before downstream use.\"],\"recommendedOperatorChecks\":[\"Confirm the source header order before editing any replay input.\",\"Verify that the observed `roles` column really contains tenant role codes in the expected delimiter format.\"],\"promptVersion\":\"import-mapping-suggestion-v1\",\"modelId\":\"gpt-4.1-mini\",\"generatedAt\":\"2026-03-27T10:30:15\",\"latencyMs\":544,\"requestId\":\"import-ai-mapping-suggestion-req-1\"}}";
    public static final String RESP_IMPORT_JOB_AI_FIX_RECOMMENDATION = "{\"code\":\"SUCCESS\",\"message\":\"ok\",\"data\":{\"importJobId\":1201,\"summary\":\"The job is mostly blocked by tenant role validation, with a smaller duplicate-username tail that should be handled as a separate cleanup step before replay.\",\"recommendedFixes\":[{\"errorCode\":\"UNKNOWN_ROLE\",\"recommendedAction\":\"Verify that the referenced role codes exist in the current tenant and normalize the source role-code format before preparing replay input.\",\"reasoning\":\"The sampled failures point to tenant role validation rather than CSV shape corruption.\",\"reviewRequired\":true,\"affectedRowsEstimate\":7},{\"errorCode\":\"DUPLICATE_USERNAME\",\"recommendedAction\":\"Review the source usernames against current-tenant users and prepare unique replacements outside the AI response before replay.\",\"reasoning\":\"The sampled failures indicate a uniqueness conflict that needs an operator-reviewed edit.\",\"reviewRequired\":true,\"affectedRowsEstimate\":2}],\"confidenceNotes\":[\"The recommendations are grounded in row-level error groups, so operators should still confirm tenant-specific business rules before reuse.\"],\"recommendedOperatorChecks\":[\"Confirm which error-code group is the highest-volume cleanup target before editing replay input.\",\"Review the affected rows in /errors so value changes can be prepared outside the AI response.\"],\"promptVersion\":\"import-fix-recommendation-v1\",\"modelId\":\"gpt-4.1-mini\",\"generatedAt\":\"2026-03-28T10:40:15\",\"latencyMs\":566,\"requestId\":\"import-ai-fix-recommendation-req-1\"}}";
    public static final String RESP_TICKET_CREATED = "{\"code\":\"SUCCESS\",\"message\":\"ok\",\"data\":{\"id\":8,\"tenantId\":1,\"title\":\"POS printer offline\",\"description\":\"Store POS printer stopped responding during lunch peak.\",\"status\":\"OPEN\",\"assigneeId\":null,\"assigneeUsername\":null,\"createdAt\":\"2026-03-11T11:00:00\",\"updatedAt\":\"2026-03-11T11:00:00\"}}";
    public static final String RESP_TICKET_ASSIGNED = "{\"code\":\"SUCCESS\",\"message\":\"ok\",\"data\":{\"id\":8,\"tenantId\":1,\"title\":\"POS printer offline\",\"description\":\"Store POS printer stopped responding during lunch peak.\",\"status\":\"OPEN\",\"assigneeId\":2,\"assigneeUsername\":\"ops\",\"createdAt\":\"2026-03-11T11:00:00\",\"updatedAt\":\"2026-03-11T11:05:00\"}}";
    public static final String RESP_TICKET_STATUS_UPDATED = "{\"code\":\"SUCCESS\",\"message\":\"ok\",\"data\":{\"id\":8,\"tenantId\":1,\"title\":\"POS printer offline\",\"description\":\"Store POS printer stopped responding during lunch peak.\",\"status\":\"IN_PROGRESS\",\"assigneeId\":2,\"assigneeUsername\":\"ops\",\"createdAt\":\"2026-03-11T11:00:00\",\"updatedAt\":\"2026-03-11T11:10:00\"}}";
    public static final String RESP_TICKET_COMMENT_CREATED = "{\"code\":\"SUCCESS\",\"message\":\"ok\",\"data\":{\"id\":51,\"ticketId\":8,\"content\":\"Checked the store network. Restarting the printer now.\",\"createdBy\":2,\"createdByUsername\":\"ops\",\"createdAt\":\"2026-03-11T11:15:00\"}}";
    public static final String RESP_FEATURE_FLAG_ITEM = "{\"code\":\"SUCCESS\",\"message\":\"ok\",\"data\":{\"id\":1,\"key\":\"ai.ticket.summary.enabled\",\"enabled\":false,\"updatedAt\":\"2026-04-06T13:30:00\"}}";
    public static final String RESP_FEATURE_FLAG_LIST = "{\"code\":\"SUCCESS\",\"message\":\"ok\",\"data\":{\"items\":[{\"id\":4,\"key\":\"ai.import.error-summary.enabled\",\"enabled\":true,\"updatedAt\":\"2026-04-06T13:18:00\"},{\"id\":6,\"key\":\"ai.import.fix-recommendation.enabled\",\"enabled\":true,\"updatedAt\":\"2026-04-06T13:18:00\"},{\"id\":5,\"key\":\"ai.import.mapping-suggestion.enabled\",\"enabled\":true,\"updatedAt\":\"2026-04-06T13:18:00\"},{\"id\":3,\"key\":\"ai.ticket.reply-draft.enabled\",\"enabled\":true,\"updatedAt\":\"2026-04-06T13:18:00\"},{\"id\":1,\"key\":\"ai.ticket.summary.enabled\",\"enabled\":true,\"updatedAt\":\"2026-04-06T13:18:00\"},{\"id\":2,\"key\":\"ai.ticket.triage.enabled\",\"enabled\":true,\"updatedAt\":\"2026-04-06T13:18:00\"},{\"id\":7,\"key\":\"workflow.import.selective-replay-proposal.enabled\",\"enabled\":true,\"updatedAt\":\"2026-04-06T13:18:00\"},{\"id\":8,\"key\":\"workflow.ticket.comment-proposal.enabled\",\"enabled\":true,\"updatedAt\":\"2026-04-06T13:18:00\"}]}}";

    public static final String RESP_DEV_PING = "{\"code\":\"SUCCESS\",\"message\":\"ok\",\"data\":{\"status\":\"UP\",\"module\":\"merchantops-api\"}}";
    public static final String RESP_DEV_ECHO = "{\"code\":\"SUCCESS\",\"message\":\"ok\",\"data\":{\"message\":\"hello merchantops\"}}";
    public static final String RESP_BIZ_ERROR = "{\"code\":\"BIZ_ERROR\",\"message\":\"demo business exception\",\"data\":null}";

    public static final String RESP_RBAC_READ_USERS = "{\"code\":\"SUCCESS\",\"message\":\"ok\",\"data\":{\"action\":\"read users\",\"result\":\"allowed\"}}";
    public static final String RESP_RBAC_MANAGE_USERS = "{\"code\":\"SUCCESS\",\"message\":\"ok\",\"data\":{\"action\":\"manage users\",\"result\":\"allowed\"}}";
}
